#!/bin/bash

# run time.ino on arduino
# run sioecho /dev/ttyACM0 on this host (opens and conditions the port)
# run this script to set the name
# $ set_arduino_name +arduino001
echo N$1 > /dev/ttyACM0
