#!/bin/bash
# this example sends data for two sio devices to vortex
sioecho /dev/ttyACM0 /dev/ttyACM1 

sleep 15

#update the time on each device
echo T$(date +%s) > /dev/ttyACM0 &
echo T$(date +%s) > /dev/ttyACM1 &
