#!/bin/bash

# run time.ino on arduino
# run sioecho /dev/ttyACM0 on this host (opens and conditions the port)
# run this script to set the time
# $ set_arduino_time /dev/ttyACM0
echo T$(date +%s) > $1
